### ISSUE TITLE
When closing document (X on top right) Collabora doesn't close

### ISSUE THREAD

**Issue by Xaldimo** [nextcloud/richdocuments#105]
### Steps to reproduce
1. Open document in NC with Collabora
2. Press X on top right corner
3.

### Expected behaviour
Collabora closes and file view returns

### Actual behaviour
Document is closed and blank Collabora page is show (still with Collabora menu bar)

### Server configuration

**Operating system**: Ubuntu 16.03

**Web server:** Apache 2.4.18

**Database:** MySQL 5.5.53

**PHP version:** 7.0.18

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 11.0.3

**Where did you install Nextcloud from:** NextCloud site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                                                                                                                                                                                      
  - activity: 2.5.2                                                                                                                                                                           
  - admin_audit: 1.2.0                                                                                                                                                                        
  - announcementcenter: 3.1.0                                                                                                                                                                 
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2                                                                                                                                                                 
  - comments: 1.2.0                                                                                                                                                                           
  - dav: 1.3.0                                                                                                                                                                                
  - deck: 0.2.0                                                                                                                                                                               
  - federatedfilesharing: 1.2.0                                                                                                                                                               
  - federation: 1.2.0                                                                                                                                                                         
  - files: 1.7.2                                                                                                                                                                              
  - files_accesscontrol: 1.2.4                                                                                                                                                                
  - files_downloadactivity: 1.1.1                                                                                                                                                             
  - files_external: 1.3.0                                                                                                                                                                     
  - files_pdfviewer: 1.1.1                                                                                                                                                                    
  - files_retention: 1.1.2                                                                                                                                                                    
  - files_sharing: 1.4.0                                                                                                                                                                      
  - files_texteditor: 2.4.1                                                                                                                                                                   
  - files_trashbin: 1.2.0                                                                                                                                                                     
  - files_versions: 1.5.0                                                                                                                                                                     
  - files_videoplayer: 1.1.0                                                                                                                                                                  
  - firstrunwizard: 2.1                                                                                                                                                                       
  - gallery: 17.0.0                                                                                                                                                                           
  - logreader: 2.0.0                                                                                                                                                                          
  - lookup_server_connector: 1.0.0                                                                                                                                                            
  - nextcloud_announcements: 1.1                                                                                                                                                              
  - notifications: 2.0.0                                                                                                                                                                      
  - oauth2: 1.0.5                                                                                                                                                                             
  - onlyoffice: 1.0.5                                                                                                                                                                         
  - passman: 2.1.2                                                                                                                                                                            
  - password_policy: 1.2.2                                                                                                                                                                    
  - previewgenerator: 1.0.6                                                                                                                                                                   
  - provisioning_api: 1.2.0                                                                                                                                                                   
  - richdocuments: 1.12.33                                                                                                                                                                    
  - serverinfo: 1.2.0                                                                                                                                                                         
  - sharebymail: 1.2.0                                                                                                                                                                        
  - sharerenamer: 1.3                                                                                                                                                                         
  - socialsharing_email: 1.0.1                                                                                                                                                                
  - socialsharing_facebook: 1.0.1
  - spreedme: 0.3.9
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - onlyoffice.old
  - theming
  - user_external
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{                                                                                                                                                                                             
    "system": {                                                                                                                                                                               
        "instanceid": "occ3bgzu13dp",                                                                                                                                                         
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                                                                                                      
        "secret": "***REMOVED SENSITIVE VALUE***",                                                                                                                                            
        "trusted_domains": [                                                                                                                                                                  
            "cloud.domain.tld"                                                                                                                                                                
        ],                                                                                                                                                                                    
        "forwarded_for_headers": [                                                                                                                                                            
            "HTTP_X_FORWARDED",                                                                                                                                                               
            "HTTP_FORWARDED_FOR",                                                                                                                                                             
            "X-Forwarded-For"                                                                                                                                                                 
        ],                                                                                                                                                                                    
        "datadirectory": "\/media\/nextcloud",                                                                                                                                                
        "overwrite.cli.url": "https:\/\/cloud.domain.tld",                                                                                                                                    
        "dbtype": "mysql",                                                                                                                                                                    
        "version": "12.0.0.29",                                                                                                                                                               
        "dbname": "nextcloud_stable",                                                                                                                                                         
        "dbhost": "192.168.7.244",                                                                                                                                                            
        "dbtableprefix": "nc_",                                                                                                                                                               
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                                                                                            
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                                                                                        
        "logtimezone": "UTC",                                                                                                                                                                 
        "installed": true,                                                                                                                                                                    
        "trusted_proxies": [                                                                                                                                                                  
            "192.168.7.241",                                                                                                                                                                  
            "192.168.7.245"                                                                                                                                                                   
        ],                                                                                                                                                                                    
        "overwriteprotocol": "https",                                                                                                                                                         
        "overwritehost": "cloud.domain.tld",                                                                                                                                                  
        "overwritewebroot": "\/",                                                                                                                                                             
        "overwritecondaddr": "^192\\.168\\.7\\.241$",                                                                                                                                         
        "mail_from_address": "cloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.tld",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud-stable.log",
        "loglevel": "0",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.domain.tld",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "session_keepalive": true,
        "activity_expire_days": 365,
        "theme": "wijman",
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Chrome Version 58.0.3029.96 (64-bit)

**Operating system:** Ubuntu 16.04 

#### Web server error log
<details>
<summary>Web server error log</summary>
```
No errors seen
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
No entries regarding Collabora for this issue
```
</details>
