### ISSUE TITLE
504 Gateway Time-out when enabling richdocuments

### ISSUE THREAD

**Issue by xabispacebiker** [nextcloud/richdocuments#1486]
**Describe the bug**
Nextcloud becomes unusable when activating richdocuments app + richdocumentscode after colaboraoffice upgrade. It was working smoothly before the update.

**To Reproduce**
Just upgrade to the latest version (using https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-debian10 repo) and activate richdocuments + richdocumentscode

**Expected behavior**
It should allow web navigation and document edition, but the server hangs with a 504 Gateway Time-out

**Screenshots**
None

**Client details:**
 - OS: MacOS Catalina
 - Browser Safari, chrome, firefox, etc..
 - Version: Safari Versión 14.0.3
 - Device: iMac, Macbook, any device

## Server details

**Operating system**:
Debian 10 Buster

**Web server:**
nginx version: nginx/1.14.2
**Database:**
mysql  Ver 15.1 Distrib 10.3.27-MariaDB
**PHP version:**
PHP 7.3.27-1~deb10u1
**Nextcloud version:**
21.
**Version of the richdocuments app**
richdocuments 4.0.4
**Version of Collabora Online**
Collabora Online - Built-in CODE Server	6.4.70

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
nothing interesting

#### Nginx log
2021/04/13 03:40:16 [error] 940#940: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: X.X.X.X, server: nextcloud.mydomain.com, request: "GET /settings/user HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock", host: "nextcloud.mydomain.com"

</details>

**Comment by RoL0NL** [comment]
I also saw this behaviour when trying the build-in richdocumentscode instead of the external CODE application I normally use when trying to solve my issue #1483 (see specs in that issue). I had to disable richdocumentscode via the CLI to make Nextcloud accessible again.

**Comment by TR4Android** [comment]
Seconding this. Also happens to me when I tried to install both richdocuments and richdocumentscode after upgrading to Nextcloud 23. Had to disable both to be able to use my Nextcloud instance again. If there's any way I can help resolve this issue or if there are known solutions please let me know.

**Operating system:** Ubuntu 20.04
**Web server:** nginx version: nginx/1.18.0 (Ubuntu)
**PHP version:** PHP 7.4.3
**Nextcloud version:** 23.0.0
**Version of richdocuments:** 5.0.2
**Version of richdocumentscode:** 21.11.103

**Comment by juliushaertl** [comment]
If you are installing Collabora separately form the CODE repository there is no need to have richdocumentscode installed. The recommendation would always be to have the full installation through docker or distribution packages for performance reasons. A gateway timeout might hint that either your coolwsd service is not running on the server or there is a misconfiguration in your Webservers reverse proxy.  

Those links might be helpful for getting this setup properly:
https://www.collaboraoffice.com/code/linux-packages/
https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html

**Comment by TR4Android** [comment]
@juliushaertl I also have a feeling this is largely independent of the CODE server. I've uninstalled the built-in CODE server and only installed the `richdocuments` app and as soon as it is installed it locks down my instance. I cannot even make it as far as the settings page for the CODE server within Nextcloud.

**Comment by KapriQ** [comment]
Is there any fix yet please? .... Latest NC + collabora , and boom, server crashed

**Comment by Hoeze** [comment]
+1 on this...
Nginx reverse proxy:
```
location /owncloud/ {
         set $upstream_host 127.0.0.1;
         set $upstream_port 8001;
         set $upstream_proto http;
 
         include /etc/nginx/proxy_params;
 
         add_header Front-End-Https on;
 
         proxy_pass $upstream_proto://$upstream_host:$upstream_port;
 
         rewrite /owncloud(.*)$ $1 break;
     }
```
docker-compose.conf:
```yaml
version: '3.3'                                                                                                                                                                                                                     [3/1427]
services: 
  nextcloud-db: 
    image: mariadb                                
    container_name: nextcloud-db                                                                                                                                                                                                           
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/containers/nextcloud/mounts/database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "<rootpw>"
        MYSQL_PASSWORD: "<mysqlpw>"
        MYSQL_DATABASE: "my_owncloud"
        MYSQL_USER: "<mysqluser>"
        MYSQL_INITDB_SKIP_TZINFO: 1
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass <redispass>
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
        TRUSTED_PROXIES: host.containers.internal
        OVERWRITEHOST: '<myhost>'
        OVERWRITEWEBROOT: '/owncloud'
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD: <redispass>
    volumes:
      - /opt/containers/nextcloud/mounts/app:/var/www/html 
      - /opt/containers/nextcloud/mounts/data:/var/www/html/data
    ports:
      - "127.0.0.1:8001:80"
```

Immediately after installing the hub packages, I get `504 Gateway Time-out`.
