### ISSUE TITLE
Run nextcloud and collabora in two separated docker container

### ISSUE THREAD

**Issue by WqyJh** [nextcloud/richdocuments#197]
I am trying to run nextcloud and collabora in two separated docker container. Since I'm now working on my local computer, I don't have an domain service and I disable the ssl verification of the collabora service.

Here is my `docker-compose.yml` file.
```yaml
version: '2'

volumes:
  data:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=xxx

  app:
    build: .
    image: nextcloud:0.2
    ports:
      - 8080:80
    restart: always
    links:
      - db
      - collabora
    depends_on:
      - db
      - collabora
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=xxx
      - NEXTCLOUD_ADMIN_PASSWORD=xxx
    volumes:
      - data:/var/www/html/data

  collabora:
    build: collabora
    image: collabora:0.1
    restart: always
    environment:
      domain: collabora
      username: xxx
      password: xxx
    cap_add:
      - MKNOD
    volumes:
      - data:/var/www/html/data
    ports:
      - 9980:9980
```

After I run these service, I got the following containers.
```bash
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
0a86425e3fcb        nextcloud:0.2       "/entrypoint.sh apac…"   17 seconds ago      Up 16 seconds       0.0.0.0:8080->80/tcp     nextcloud_app_1
d4c66ccfac3e        collabora/code      "/bin/sh -c 'bash st…"   32 seconds ago      Up 30 seconds       0.0.0.0:9980->9980/tcp   nextcloud_collabora_1
ca80b694d6f5        mariadb             "docker-entrypoint.s…"   3 hours ago         Up 3 hours          3306/tcp                 nextcloud_db_1
```

Then I was able to open the nextcloud site on `127.0.0.1:8080` and the collabora site on `127.0.0.1:9980`。

Problems occurred when I tried to open a `.odt` document file on the nextcloud site, it told me "sorry, unable to connect to my document, please retry".
I checked the logs and found that the collabora site got failed when trying to access the nextcloud site by `127.0.0.1:8080`. Following is the logs.

```bash
wsd-00030-00072 05:14:43.300960 [ docbroker_009 ] ERR  Cannot get file info from WOPI storage uri [http://127.0.0.1:8080/apps/richdocuments/wopi/files/14_och6b9f6f7wg?access_token=GKDBLNqN1CEEWKlHgUL1WC8lImxU2GzR&access_token_ttl=0&permission=edit]. Error: Connection refused| wsd/Storage.cpp:529
wsd-00030-00072 05:14:43.301062 [ docbroker_009 ] ERR  Failed to add session to [/apps/richdocuments/wopi/files/14_och6b9f6f7wg] with URI [http://127.0.0.1:8080/apps/richdocuments/wopi/files/14_och6b9f6f7wg?access_token=GKDBLNqN1CEEWKlHgUL1WC8lImxU2GzR&access_token_ttl=0&permission=edit]: Connection refused| wsd/DocumentBroker.cpp:1000
wsd-00030-00072 05:14:43.301104 [ docbroker_009 ] ERR  Error while loading : Connection refused| wsd/LOOLWSD.cpp:2333
```

Because the two sites run on different docker container, the collabora site apparently cannot access the other by `127.0.0.1:8080`.

Then I check the page source and find that the `127.0.0.1:8080` is part of a `form action url`, this url was sent to the collabora site and told the site where to find the document file, which I think cause the problem. The `127.0.0.1:8080` written in that url was considered as the actually location of the nextcloud site by the frontend program, while the collabora site can't access the nextcloud site by `127.0.0.1:8080`, which could also be a public accessible `domain name`, or `hostname`, or ip of other network interface card such as `172.18.0.4:8080`, not all of them could be accessed by the collabora site.

The problem is, how can I handle this when I work on my local computer without an domain service to help the two container find each other?  (How to make them mutual accessible?)
