### ISSUE TITLE
public_wopi_url is automatically detected incorrectly and cannot be set manually.

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/richdocuments#1990]
**Describe the bug**
Url is automatically detected incorrectly and cannot be set manually.

**To Reproduce**
```
# Check boths URLs
php occ config:app:get richdocuments wopi_url
php occ config:app:get richdocuments public_wopi_url

# Set Url
php occ config:app:set richdocuments public_wopi_url --value=https:\/\/cloud-test.borntoberoot.net\/custom_apps\/richdocumentscode\/proxy.php?req=

# Check URL again (it's correct)
php occ config:app:get richdocuments public_wopi_url

# Activate config
php occ richdocuments:activate-config

# Check again (it's not correct, again)
php occ config:app:get richdocuments public_wopi_url
```

![image](https://user-images.githubusercontent.com/16019165/149675461-a531d3f2-a8a6-4682-8080-e10b74654313.png)

**Expected behavior**
URL is set correct after this.

**Screenshots**
URL is wrong
![image](https://user-images.githubusercontent.com/16019165/149675618-0ad41726-7aca-4508-b34d-80200abd9c2a.png)

## Server details

Latest docker-image: nextcloud:23-apache
Latest collabora app via AppStore: richdocuments, richdocumentscode (x86/x64)

**Comment by BornToBeRoot** [comment]
If i don't activate the conifg, the url is still wrong but i get another error in chrome:

![image](https://user-images.githubusercontent.com/16019165/149675779-5f1da05e-3ff6-4d7a-985b-10df5887f912.png)

**Comment by BornToBeRoot** [comment]
@juliushaertl Any idea how to change the url or detect the proxy correct?

**Comment by BornToBeRoot** [comment]
I setup the collabora code server via docker and had to set the variable `server_name` to my external domain of collabora:

```
  # Collabora office
  office:
    image: collabora/code:latest
    container_name: nextcloud_${ID}_office
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - domain=cloud.example.com
      - username=admin
      - password=123456
      - server_name=office.example.com
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud_${ID}_office.rule=Host(`office.internal.example.com`)"
      - "traefik.http.routers.nextcloud_${ID}_office.entrypoints=websecure"
      - "traefik.http.routers.nextcloud_${ID}_office.tls.certresolver=dns"
      - "traefik.http.routers.nextcloud_${ID}_office.tls=true"
      - "traefik.http.services.nextcloud_${ID}_office.loadbalancer.server.port=9980"
      - "traefik.docker.network=traefik_proxy"
```

Before setting `server_name` the `public_wopi_url` was automaticaly set to `office.internal.example.com`. Since this domain is not reachable from the internet, the documents failed to load.

Would be great if we can set/override the `server_name` for the build in code server.
