### ISSUE TITLE
Failed to connect to nextcloud office with collabora

### ISSUE THREAD

**Issue by UltraBlackLinux** [nextcloud/richdocuments#3197]
**Describe the bug**
About two days ago I first set up nextcloud, but I had to reinstall twice, and since that first attempt (on 27.0.7 afaik), collabora no longer worked ever again. When I open a libreoffice document all it does is load for a while and then complain about being unable to open nextcloud office.

**To Reproduce**
1. Install [the nextcloud community image](https://hub.docker.com/_/nextcloud/) (I haven't tried the AIO image since that's a PITA to set up and pretty much forces me to test on prod)
3. Install Nextcloud office
4. Install the built-in collabora server or spin up the [official collabora docker image](https://hub.docker.com/r/collabora/code/)
5. Check the settings: It can find the server
6. Open a libreoffice document
7. "Failed to open nextcloud office"

**Expected behavior**
It should open the document

**Client details:**
- OS: Arch Linux
- Browser Firefox
- Version 117.01
- Device: Desktop

## Server details
**Operating system**: Arch Linux (don't question it 😉)
**Web server:** Apache
**Database:** Mariadb
**PHP version:** Built into the docker image, no idea
**Nextcloud version:** 27.0.7-27.1.1
**Version of the richdocuments app** 8.2.0
**Version of Collabora Online** 23.05.4.2.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
**if this is what I can also see in the admin console, this is probably not of any use. The admin console showed absolutely no info about te collabora problem. Those timeouts are 30 minutes old and probably unrelated**
[nextcloud.log](https://github.com/nextcloud/richdocuments/files/12706246/nextcloud.log)

#### Browser log
[console-export-2023-9-23_12-51-16.txt](https://github.com/nextcloud/richdocuments/files/12706247/console-export-2023-9-23_12-51-16.txt)
</details>

Test dockerfile:
(untested, edited version of mine, should still be able to showcase the problem)
Install collabora into nextcloud:
```
docker exec -u 33 nextcloud php -d memory_limit=512M ./occ app:install richdocuments
docker exec -u 33 nextcloud php -d memory_limit=512M ./occ app:install richdocumentscode
```
try the built-in server and the docker container at `nextcloud-collabora:9980`

```yml
version: '3'

networks:
    nextcloud-db:
    nextcloud-collabora:
    
volumes:
    nextcloud:
    nextcloud-db:

services:
    nextcloud-db:
        image: docker.io/mariadb:latest
        container_name: nextcloud-db
        restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - nextcloud-db:/var/lib/mysql
        networks:
            - nextcloud-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=nc
            - MYSQL_DATABASE=nc
            - MYSQL_USER=nc

    nextcloud-collabora:
        image: docker.io/collabora/code:23.05.4.2.1
        container_name: nextcloud-collabora
        restart: always
        networks:
            - nextcloud-collabora
        environment:
            - "extra_params=--o:ssl.enable=false"

    nextcloud:
        build: docker.io/nextcloud:27
        container_name: nextcloud
        restart: always
        networks:
            - nextcloud-db
            - nextcloud-collabora
        volumes:
            - nextcloud:/var/www/html
        ports:
            - 80:80
        environment:
            - MYSQL_PASSWORD=nc
            - MYSQL_DATABASE=nc
            - MYSQL_USER=nc
            - MYSQL_HOST=nextcloud-db
```
