### ISSUE TITLE
Side by side comparison of document versions broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#3357]
**Describe the bug**

I can no longer compare versions of a document side-by-side

**To Reproduce**
1. Create a office document
2. edit it multiple times
3. close the document and go to the right sidebar
4. got to versions
5. click the "..." menu of one of the versions and chose "compare to current version"

**Expected behavior**
side-by-side read only view of the current version of the document and the selected version.

Instead the document opens full screen. 

Tested with Hub7 on c.nc.com (worked with Hub6)

**Comment by juliushaertl** [comment]
Quick styling fix could be this, but would probably be better to check on where this broke (likely with some upstream styling changes in viewer)

```css
.viewer--split .office-viewer.viewer__file--active {
	width: 50%;

	&:nth-child(1) {
		left:0;
	}
	&:nth-child(2) {
		left:50%;
	}
}
```
